config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  get "/search", to: "searches#search"
  
  #patch 'books/:id' => "books#edit", as: "edit"
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
        resource :favorite, only: [:create, :destroy]
        resources :book_comments, only: [:create]
  end
  resources :book_comments, only: [:destroy]
  
  resources :users, only: [:index, :show, :edit, :update] do
        resource :relationships, only: [:create, :destroy]
      	get "followings" => "relationships#followings", as: "followings"
  	    get "followers" => "relationships#followers", as: "followers"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :ensure_correct_user, only: [:destroy] 
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(book)
    else
      redirect_to book_path(book)
    end
  end

  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
  def ensure_correct_user
    book_comment = BookComment.find(params[:id])
    unless book_comment.user_id == current_user.id
    redirect_back(fallback_location: root_path)
    end
  end
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_bookcomments.html.erb
<tbody>
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= link_to user_path(book_comment.user_id) do %>
        <%= image_tag book_comment.user.get_profile_image, size:'50x50' %><br>
        <%= book_comment.user.name %>
        <% end %>
    </td>
    <td>
      <%= book_comment.comment %>
    </td> 
    <td>
      <% if book_comment.user_id == current_user.id %>
        <%= link_to "Destroy", book_comment_path(book_comment), method: :delete, class: "btn-sm btn-danger" %>
      <% end %>
    </td>
  </tr><td>
  <% end %>  
</tbody>